#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2021040700
#cyc=00
#fhr=54
#domain='conus'

echo 'into launchUHTRACKS'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam/$cyc
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/fv3nam/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_nam/plot_uhtracks.py $CDATE $domain

exit


