#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2019041100
#cyc=00

echo 'into launchQPF'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/fv3nam/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_nam/plot_fv3_qpf_dif.py $CDATE $domain 
wait


exit

