#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2019020800
#cyc=00
#fhr=54

echo 'into launchALL'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam/$cyc
mkdir -p /gpfs/dell3/stmp/${USER}/fv3nam/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/fv3nam/$CDATE/$cyc

PDY=`echo $CDATE | cut -c1-8`
#gridspecs="lambert:262.5:38.5:38.5 237.280:1799:3000 21.138:1059:3000"
#wgrib2 /gpfs/dell1/nco/ops/com/nam/prod/nam.${PDY}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00.grib2 -new_grid_winds grid -new_grid ${gridspecs} nam.t${cyc}z.conusnest.hiresf${fhr}.tm00.grib2
#sleep 90

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_nam/plot_allvars1.py $CDATE $fhr

exit


