#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2021082300
#cyc=00
#domain=conus

echo 'into launchQPF'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/4panel
mkdir -p /gpfs/dell3/stmp/${USER}/4panel/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/4panel/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/4panel/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/create_4panel/plot_4panel_qpf.py $CDATE $domain 
wait


exit

