#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2020010700
#cyc=00
#fhr=00

echo 'into launchALL'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell2/stmp/${USER}
mkdir -p /gpfs/dell2/stmp/${USER}/fv3test
mkdir -p /gpfs/dell2/stmp/${USER}/fv3test/$cyc
cd /gpfs/dell2/stmp/${USER}/fv3test/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_da/plot_allvars3.py $CDATE $fhr

exit


