#!/bin/ksh
set -x

USER=Benjamin.Blake
CDATE=2020121500
cyc=00

echo 'into launchPTYPE'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/test
mkdir -p /gpfs/dell3/stmp/${USER}/test/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/test/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/test/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_lams/plot_fv3_ptype_dif.py $CDATE conus
wait

exit
