#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2021040800
#cyc=00
#fhr=48
#domain='conus'

echo 'into launchUHTRACKS'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/lams
mkdir -p /gpfs/dell3/stmp/${USER}/lams/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/lams/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/lams/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_lams/plot_uhtracks.py $CDATE $domain

exit


