#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2019040500
#cyc=00

echo 'into launchCLOUD'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/lams
mkdir -p /gpfs/dell3/stmp/${USER}/lams/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/lams/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/lams/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_lams/plot_fv3_cloud_dif.py $CDATE $domain
wait


exit

