#!/bin/ksh
set -x

USER=Benjamin.Blake
CDATE=2020111000
cyc=00
domain=conus

echo 'into launchCLOUD'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/fv3test
mkdir -p /gpfs/dell3/stmp/${USER}/fv3test/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/fv3test/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/fv3test/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/compare_lams/plot_fv3_cloud_dif.py $CDATE $domain
wait


exit

