#!/bin/ksh
set -x

USER=Benjamin.Blake
CDATE=2021081212
cyc=12
fhr=1

echo 'into launchTEST'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/test
mkdir -p /gpfs/dell3/stmp/${USER}/test/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/test/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/test/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/create_lamx/plot_allvars_akhipr_test.py $CDATE $fhr

exit

