#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2020112212
#cyc=12
#domain=ak

echo 'into launchCLOUD'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/oconus
mkdir -p /gpfs/dell3/stmp/${USER}/oconus/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/oconus/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/oconus/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/create_oconus/plot_cloud.py $CDATE $domain
wait


exit

