#!/bin/ksh
set -x

#USER=Benjamin.Blake
#CDATE=2021010600
#cyc=00
#domain=namerica

echo 'into launchPTYPE'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/oconus
mkdir -p /gpfs/dell3/stmp/${USER}/oconus/$CDATE
mkdir -p /gpfs/dell3/stmp/${USER}/oconus/$CDATE/$cyc
cd /gpfs/dell3/stmp/${USER}/oconus/$CDATE/$cyc

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/create_oconus/plot_ptype.py $CDATE $domain
wait


exit

