#!/bin/ksh
set -x

#USER=Shun.Liu
#CDATE=2021030200
#cyc=00

#PDY=`echo $CDATE | cut -c1-8`

#if [ $cyc = 00 ]; then
#  cycm1=12
#  PDYm1=20210301
#elif [ $cyc = 12 ]; then
#  cycm1=00
#  PDYm1=`echo $CDATE | cut -c1-8`
#fi

echo 'into launchINCREMENTS'
. /usrx/local/prod/lmod/lmod/init/sh
source /u/${USER}/bin/loadp.sh
module load imagemagick/6.9.9-25

mkdir -p /gpfs/dell3/stmp/${USER}
mkdir -p /gpfs/dell3/stmp/${USER}/increments
mkdir -p /gpfs/dell3/stmp/${USER}/increments/$CDATE
cd /gpfs/dell3/stmp/${USER}/increments/$CDATE

# Retrieve placeholder for the tm06 images that are unavailable
if [ $tmmark = tm06 ]; then
  cp /gpfs/dell2/emc/modeling/noscrub/Shun.Liu/python.fv3/monitor/Placeholder2.png tlvl1_conus_tm06.png
  cp /gpfs/dell2/emc/modeling/noscrub/Shun.Liu/python.fv3/monitor/Placeholder2.png qlvl1_conus_tm06.png
  cp /gpfs/dell2/emc/modeling/noscrub/Shun.Liu/python.fv3/monitor/Placeholder2.png wspdlvl1_conus_tm06.png
fi

# Retrieve GDAS file for tm06 and use wgrib2 to interpolate to the correct output grid
gridspecs="lambert:262.5:38.5:38.5 237.280:1799:3000 21.138:1059:3000"
wgrib2 /gpfs/dell1/nco/ops/com/gfs/prod/gdas.${PDYm1}/${cycm1}/atmos/gdas.t${cycm1}z.pgrb2.0p25.f006 -new_grid_winds grid -new_grid ${gridspecs} gdas.t${cyc}z.guess.tm06.grib2
#wgrib2 /gpfs/dell1/nco/ops/com/gfs/prod/gdas.${PDYm1}/${cycm1}/atmos/gdas.t${cycm1}z.pgrb2b.0p25.f006 -new_grid_winds grid -new_grid ${gridspecs} gdas.t${cyc}z.guess2.tm06.grib2

# Run Python scripts - submit a separate job for each tmmark with Rocoto

python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/monitor/increments_lamda.py ${CDATE} ${tmmark}
python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/monitor/increments_rdas_conus.py ${CDATE} ${tmmark}
#python /gpfs/dell2/emc/modeling/noscrub/${USER}/python.fv3/monitor/increments_lamdax.py ${CDATE} ${tmmark}

if [ $tmmark != tm06 ]; then
  convert lamda_tlvl1_conus_${tmmark}.png rdas_tlvl1_conus_${tmmark}.png +append tlvl1_conus_${tmmark}.png
  convert lamda_qlvl1_conus_${tmmark}.png rdas_qlvl1_conus_${tmmark}.png +append qlvl1_conus_${tmmark}.png
  convert lamda_wspdlvl1_conus_${tmmark}.png rdas_wspdlvl1_conus_${tmmark}.png +append wspdlvl1_conus_${tmmark}.png
fi
convert lamda_slp_conus_${tmmark}.png rdas_slp_conus_${tmmark}.png +append slp_conus_${tmmark}.png
convert lamda_pw_conus_${tmmark}.png rdas_pw_conus_${tmmark}.png +append pw_conus_${tmmark}.png
convert lamda_z850_conus_${tmmark}.png rdas_z850_conus_${tmmark}.png +append z850_conus_${tmmark}.png
convert lamda_z700_conus_${tmmark}.png rdas_z700_conus_${tmmark}.png +append z700_conus_${tmmark}.png
convert lamda_z500_conus_${tmmark}.png rdas_z500_conus_${tmmark}.png +append z500_conus_${tmmark}.png
convert lamda_z250_conus_${tmmark}.png rdas_z250_conus_${tmmark}.png +append z250_conus_${tmmark}.png
convert lamda_t850_conus_${tmmark}.png rdas_t850_conus_${tmmark}.png +append t850_conus_${tmmark}.png
convert lamda_t700_conus_${tmmark}.png rdas_t700_conus_${tmmark}.png +append t700_conus_${tmmark}.png
convert lamda_t500_conus_${tmmark}.png rdas_t500_conus_${tmmark}.png +append t500_conus_${tmmark}.png
convert lamda_t250_conus_${tmmark}.png rdas_t250_conus_${tmmark}.png +append t250_conus_${tmmark}.png
convert lamda_q850_conus_${tmmark}.png rdas_q850_conus_${tmmark}.png +append q850_conus_${tmmark}.png
convert lamda_q700_conus_${tmmark}.png rdas_q700_conus_${tmmark}.png +append q700_conus_${tmmark}.png
convert lamda_q500_conus_${tmmark}.png rdas_q500_conus_${tmmark}.png +append q500_conus_${tmmark}.png
convert lamda_wspd850_conus_${tmmark}.png rdas_wspd850_conus_${tmmark}.png +append wspd850_conus_${tmmark}.png
convert lamda_wspd700_conus_${tmmark}.png rdas_wspd700_conus_${tmmark}.png +append wspd700_conus_${tmmark}.png
convert lamda_wspd500_conus_${tmmark}.png rdas_wspd500_conus_${tmmark}.png +append wspd500_conus_${tmmark}.png
convert lamda_wspd250_conus_${tmmark}.png rdas_wspd250_conus_${tmmark}.png +append wspd250_conus_${tmmark}.png

exit


